SELECT aggfnoid,
       aggkind,
       aggnumdirectargs,
       aggtransfn,
       aggfinalfn,
       aggcombinefn,
       aggserialfn,
       aggdeserialfn,
       aggmtransfn,
       aggminvtransfn,
       aggmfinalfn,
       aggfinalextra,
       aggmfinalextra,
       aggfinalmodify,
       aggmfinalmodify,
       aggsortop,
       aggtranstype,
       aggtransspace,
       aggmtranstype,
       aggmtransspace,
       agginitval,
       aggminitval
FROM pg_catalog.pg_aggregate
LIMIT 1000;